#version 450

#extension GL_EXT_texture_shadow_lod : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2DArrayShadow sourceDepth;
layout(set = 0, binding = 1, std430) buffer Output {
    uint values[12];
} outputBuffer;

void main() {
    uint layer = gl_GlobalInvocationID.x;
    float value = textureLod(
        sourceDepth, vec4(0.5, 0.5, float(layer), 0.5), 0.0);
    outputBuffer.values[layer] = uint(round(clamp(value, 0.0, 1.0)));
}
