#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0, rgba8) uniform readonly image2D sourceImage;
layout(set = 0, binding = 1, std430) buffer Output {
    uint value;
} outputBuffer;
void main() {
    vec4 value = imageLoad(sourceImage, ivec2(0, 0));
    uvec4 color = uvec4(round(clamp(value, 0.0, 1.0) * 255.0));
    outputBuffer.value = color.x | (color.y << 8) | (color.z << 16) | (color.w << 24);
}
